version: "3.8"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"     # Web UI
      - "14268:14268"     # Collector (HTTP)
    # при необходимости добавьте порты агента:
    # - "6831:6831/udp"
    # - "6832:6832/udp"

  router:
    build:
      context: ./router
    container_name: router
    ports:
      - "8081:8081"
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_SERVICE_NAME=router
    depends_on:
      - jaeger

  pay:
    build:
      context: ./pay
    container_name: pay
    ports:
      - "9090:9090"
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_SERVICE_NAME=pay
    depends_on:
      - jaeger
